#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 146
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 18

enum {
  sym_identifier = 1,
  sym_comment = 2,
  sym__quoted_string_content = 3,
  anon_sym_DQUOTE = 4,
  sym__line_string_content = 5,
  anon_sym_DASH_DASH = 6,
  anon_sym_0 = 7,
  aux_sym_number_token1 = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  anon_sym_BSLASH = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_GT = 14,
  anon_sym_LT = 15,
  anon_sym_EQ = 16,
  anon_sym_not = 17,
  anon_sym_and = 18,
  anon_sym_or = 19,
  anon_sym_LPAREN2 = 20,
  anon_sym_COMMA = 21,
  anon_sym_package = 22,
  anon_sym_import = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  anon_sym_using = 26,
  anon_sym_document = 27,
  anon_sym_component = 28,
  anon_sym_COLON = 29,
  anon_sym_POUND = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  anon_sym_SLASH = 33,
  sym__ignored = 34,
  sym_source_file = 35,
  sym__identifier_or_member_access = 36,
  sym__string_quoted = 37,
  sym__string_line = 38,
  sym_string = 39,
  sym_number = 40,
  sym_bool = 41,
  sym__primary_expression = 42,
  sym_template_expression = 43,
  sym__expression = 44,
  sym_operator = 45,
  sym_call = 46,
  sym_package_declaration = 47,
  sym_import_declaration = 48,
  sym__using_single = 49,
  sym__using_multiple = 50,
  sym_using_declaration = 51,
  sym_document_declaration = 52,
  sym_component_declaration = 53,
  sym_properties = 54,
  sym_property = 55,
  sym_element = 56,
  sym__element_content = 57,
  sym_attributes = 58,
  sym_attribute = 59,
  sym_member_access = 60,
  sym_template = 61,
  aux_sym__imports = 62,
  aux_sym_source_file_repeat1 = 63,
  aux_sym_source_file_repeat2 = 64,
  aux_sym__string_quoted_repeat1 = 65,
  aux_sym__string_line_repeat1 = 66,
  aux_sym_call_repeat1 = 67,
  aux_sym__using_multiple_repeat1 = 68,
  aux_sym_properties_repeat1 = 69,
  aux_sym_element_repeat1 = 70,
  aux_sym__element_content_repeat1 = 71,
  aux_sym_attributes_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym__quoted_string_content] = "_quoted_string_content",
  [anon_sym_DQUOTE] = "\"",
  [sym__line_string_content] = "_line_string_content",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_0] = "0",
  [aux_sym_number_token1] = "number_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_package] = "package",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_using] = "using",
  [anon_sym_document] = "document",
  [anon_sym_component] = "component",
  [anon_sym_COLON] = ":",
  [anon_sym_POUND] = "#",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SLASH] = "/",
  [sym__ignored] = "_ignored",
  [sym_source_file] = "source_file",
  [sym__identifier_or_member_access] = "_identifier_or_member_access",
  [sym__string_quoted] = "_string_quoted",
  [sym__string_line] = "_string_line",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_bool] = "bool",
  [sym__primary_expression] = "_primary_expression",
  [sym_template_expression] = "template_expression",
  [sym__expression] = "_expression",
  [sym_operator] = "operator",
  [sym_call] = "call",
  [sym_package_declaration] = "package_declaration",
  [sym_import_declaration] = "import_declaration",
  [sym__using_single] = "_using_single",
  [sym__using_multiple] = "_using_multiple",
  [sym_using_declaration] = "using_declaration",
  [sym_document_declaration] = "document_declaration",
  [sym_component_declaration] = "component_declaration",
  [sym_properties] = "properties",
  [sym_property] = "property",
  [sym_element] = "element",
  [sym__element_content] = "children",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_member_access] = "member_access",
  [sym_template] = "template",
  [aux_sym__imports] = "_imports",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym__string_quoted_repeat1] = "_string_quoted_repeat1",
  [aux_sym__string_line_repeat1] = "_string_line_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym__using_multiple_repeat1] = "_using_multiple_repeat1",
  [aux_sym_properties_repeat1] = "properties_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym__element_content_repeat1] = "_element_content_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym__quoted_string_content] = sym__quoted_string_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__line_string_content] = sym__line_string_content,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_document] = anon_sym_document,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym__ignored] = sym__ignored,
  [sym_source_file] = sym_source_file,
  [sym__identifier_or_member_access] = sym__identifier_or_member_access,
  [sym__string_quoted] = sym__string_quoted,
  [sym__string_line] = sym__string_line,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_bool] = sym_bool,
  [sym__primary_expression] = sym__primary_expression,
  [sym_template_expression] = sym_template_expression,
  [sym__expression] = sym__expression,
  [sym_operator] = sym_operator,
  [sym_call] = sym_call,
  [sym_package_declaration] = sym_package_declaration,
  [sym_import_declaration] = sym_import_declaration,
  [sym__using_single] = sym__using_single,
  [sym__using_multiple] = sym__using_multiple,
  [sym_using_declaration] = sym_using_declaration,
  [sym_document_declaration] = sym_document_declaration,
  [sym_component_declaration] = sym_component_declaration,
  [sym_properties] = sym_properties,
  [sym_property] = sym_property,
  [sym_element] = sym_element,
  [sym__element_content] = sym__element_content,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_member_access] = sym_member_access,
  [sym_template] = sym_template,
  [aux_sym__imports] = aux_sym__imports,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym__string_quoted_repeat1] = aux_sym__string_quoted_repeat1,
  [aux_sym__string_line_repeat1] = aux_sym__string_line_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym__using_multiple_repeat1] = aux_sym__using_multiple_repeat1,
  [aux_sym_properties_repeat1] = aux_sym_properties_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym__element_content_repeat1] = aux_sym__element_content_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_string_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__line_string_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_document] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_or_member_access] = {
    .visible = false,
    .named = true,
  },
  [sym__string_quoted] = {
    .visible = false,
    .named = true,
  },
  [sym__string_line] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_template_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__using_single] = {
    .visible = false,
    .named = true,
  },
  [sym__using_multiple] = {
    .visible = false,
    .named = true,
  },
  [sym_using_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_document_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym__element_content] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__imports] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__string_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__string_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__using_multiple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_properties_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__element_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument = 1,
  field_directive = 2,
  field_from = 3,
  field_function = 4,
  field_key = 5,
  field_member = 6,
  field_name = 7,
  field_object = 8,
  field_path = 9,
  field_tag = 10,
  field_type = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_directive] = "directive",
  [field_from] = "from",
  [field_function] = "function",
  [field_key] = "key",
  [field_member] = "member",
  [field_name] = "name",
  [field_object] = "object",
  [field_path] = "path",
  [field_tag] = "tag",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 1},
  [14] = {.index = 17, .length = 2},
  [15] = {.index = 19, .length = 2},
  [16] = {.index = 21, .length = 2},
  [17] = {.index = 23, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 2},
    {field_path, 3},
  [3] =
    {field_name, 2},
  [4] =
    {field_name, 0},
    {field_type, 2},
  [6] =
    {field_tag, 1},
  [7] =
    {field_name, 1, .inherited = true},
  [8] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [10] =
    {field_from, 3},
    {field_name, 2, .inherited = true},
  [12] =
    {field_member, 2},
    {field_object, 0},
  [14] =
    {field_object, 0},
  [15] =
    {field_function, 1},
  [16] =
    {field_argument, 0},
  [17] =
    {field_directive, 0},
    {field_directive, 1},
  [19] =
    {field_key, 0},
    {field_value, 2},
  [21] =
    {field_argument, 2, .inherited = true},
    {field_function, 1},
  [23] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [3] = sym_string,
  },
  [9] = {
    [0] = sym_string,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__string_quoted, 2,
    sym__string_quoted,
    sym_string,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 15,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 21,
  [40] = 34,
  [41] = 25,
  [42] = 42,
  [43] = 43,
  [44] = 24,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 45,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 45,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 120,
  [141] = 120,
  [142] = 142,
  [143] = 143,
  [144] = 123,
  [145] = 123,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__quoted_string_content);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__quoted_string_content);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__quoted_string_content);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__line_string_content);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__line_string_content);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__line_string_content);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__line_string_content);
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__line_string_content);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 27:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_document);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_component);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 1, .external_lex_state = 2},
  [25] = {.lex_state = 1, .external_lex_state = 2},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 1, .external_lex_state = 2},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 2, .external_lex_state = 2},
  [41] = {.lex_state = 2, .external_lex_state = 2},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 2, .external_lex_state = 2},
  [45] = {.lex_state = 1, .external_lex_state = 2},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 2, .external_lex_state = 2},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 3, .external_lex_state = 3},
  [58] = {.lex_state = 3, .external_lex_state = 3},
  [59] = {.lex_state = 3, .external_lex_state = 3},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 8},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 8},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 8},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 8},
  [84] = {.lex_state = 8},
  [85] = {.lex_state = 3, .external_lex_state = 3},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 8},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 8},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 8},
  [111] = {.lex_state = 8},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 8},
  [114] = {.lex_state = 8},
  [115] = {.lex_state = 8},
  [116] = {.lex_state = 8},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 4},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 4},
  [145] = {.lex_state = 4},
};

enum {
  ts_external_token__quoted_string_content = 0,
  ts_external_token__line_string_content = 1,
  ts_external_token__ignored = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__quoted_string_content] = sym__quoted_string_content,
  [ts_external_token__line_string_content] = sym__line_string_content,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__line_string_content] = true,
  },
  [3] = {
    [ts_external_token__quoted_string_content] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_document] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(121),
    [sym_package_declaration] = STATE(48),
    [sym_import_declaration] = STATE(35),
    [sym_document_declaration] = STATE(63),
    [sym_component_declaration] = STATE(70),
    [aux_sym__imports] = STATE(35),
    [aux_sym_source_file_repeat2] = STATE(70),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN2] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    STATE(4), 1,
      aux_sym_call_repeat1,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [41] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    STATE(5), 1,
      aux_sym_call_repeat1,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [79] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      aux_sym_call_repeat1,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [117] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      aux_sym_call_repeat1,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [155] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(30), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 1,
      anon_sym_LPAREN2,
    STATE(6), 1,
      aux_sym_call_repeat1,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(33), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(36), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(44), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(46), 11,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [218] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      anon_sym_DASH_DASH,
    ACTIONS(54), 1,
      anon_sym_RPAREN,
    ACTIONS(56), 1,
      anon_sym_LPAREN2,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(8), 3,
      sym__element_content,
      sym_attributes,
      aux_sym_element_repeat1,
    STATE(20), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [254] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_DASH_DASH,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(71), 1,
      anon_sym_POUND,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(8), 3,
      sym__element_content,
      sym_attributes,
      aux_sym_element_repeat1,
    STATE(20), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [290] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(95), 6,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym__expression,
      sym_call,
      sym_member_access,
  [322] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_DASH_DASH,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(71), 1,
      anon_sym_POUND,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(9), 3,
      sym__element_content,
      sym_attributes,
      aux_sym_element_repeat1,
    STATE(20), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [358] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(79), 11,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 10,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [401] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(87), 10,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [422] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(141), 4,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym_call,
  [452] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(140), 4,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym_call,
  [482] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(23), 1,
      sym__string_quoted,
    ACTIONS(13), 2,
      anon_sym_0,
      aux_sym_number_token1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(120), 4,
      sym_number,
      sym_bool,
      sym__primary_expression,
      sym_call,
  [512] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(95), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [533] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN2,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
    ACTIONS(103), 3,
      anon_sym_not,
      anon_sym_and,
      anon_sym_or,
    STATE(3), 3,
      sym_operator,
      sym_call,
      sym_member_access,
  [558] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_DASH_DASH,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    ACTIONS(105), 3,
      anon_sym_RPAREN,
      anon_sym_POUND,
      anon_sym_LBRACE,
    STATE(21), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [585] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(110), 1,
      anon_sym_DASH_DASH,
    ACTIONS(115), 1,
      anon_sym_LPAREN2,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    ACTIONS(113), 3,
      anon_sym_RPAREN,
      anon_sym_POUND,
      anon_sym_LBRACE,
    STATE(21), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [612] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(118), 9,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [630] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(122), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [648] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym__line_string_content,
    ACTIONS(130), 1,
      anon_sym_BSLASH,
    STATE(34), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(126), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [670] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_BSLASH,
    ACTIONS(134), 1,
      sym__line_string_content,
    STATE(24), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(132), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(138), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [710] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(140), 1,
      anon_sym_DASH_DASH,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(128), 1,
      sym_template,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(37), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(146), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(154), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [792] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(140), 1,
      anon_sym_DASH_DASH,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(118), 1,
      sym_template,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(37), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [820] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(150), 7,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [838] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(140), 1,
      anon_sym_DASH_DASH,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(131), 1,
      sym_template,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(37), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [866] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym__line_string_content,
    ACTIONS(165), 1,
      anon_sym_BSLASH,
    STATE(34), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(160), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [888] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 1,
      anon_sym_LPAREN2,
    STATE(72), 1,
      sym_document_declaration,
    STATE(46), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
    STATE(74), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(77), 2,
      sym_import_declaration,
      aux_sym__imports,
  [913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(172), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(174), 5,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [932] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_LPAREN2,
    ACTIONS(140), 1,
      anon_sym_DASH_DASH,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(39), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [957] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN2,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    STATE(83), 1,
      sym_document_declaration,
    STATE(47), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
    STATE(77), 2,
      sym_import_declaration,
      aux_sym__imports,
    STATE(84), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [982] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 1,
      anon_sym_LPAREN2,
    ACTIONS(182), 1,
      anon_sym_DASH_DASH,
    STATE(50), 2,
      sym__string_quoted,
      sym__string_line,
    STATE(39), 3,
      sym_string,
      sym_element,
      aux_sym__element_content_repeat1,
  [1007] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__line_string_content,
    ACTIONS(188), 1,
      anon_sym_BSLASH,
    STATE(40), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(160), 4,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1027] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym__line_string_content,
    ACTIONS(193), 1,
      anon_sym_BSLASH,
    STATE(44), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(132), 4,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1047] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(197), 5,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1063] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(201), 5,
      anon_sym_DQUOTE,
      anon_sym_0,
      aux_sym_number_token1,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1079] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_BSLASH,
    ACTIONS(203), 1,
      sym__line_string_content,
    STATE(40), 2,
      sym_template_expression,
      aux_sym__string_line_repeat1,
    ACTIONS(126), 4,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1099] = 2,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(205), 8,
      anon_sym_DQUOTE,
      sym__line_string_content,
      anon_sym_DASH_DASH,
      anon_sym_BSLASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1113] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 1,
      anon_sym_LPAREN2,
    STATE(83), 1,
      sym_document_declaration,
    STATE(80), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
    STATE(84), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1134] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LPAREN2,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    STATE(68), 1,
      sym_document_declaration,
    STATE(60), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(80), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
  [1155] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 1,
      anon_sym_LPAREN2,
    STATE(72), 1,
      sym_document_declaration,
    STATE(38), 2,
      sym_import_declaration,
      aux_sym__imports,
    STATE(74), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1212] = 2,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(205), 6,
      anon_sym_DQUOTE,
      sym__line_string_content,
      anon_sym_DASH_DASH,
      anon_sym_BSLASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1248] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 6,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_POUND,
      anon_sym_LBRACE,
  [1272] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym__quoted_string_content,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      anon_sym_BSLASH,
    STATE(59), 2,
      sym_template_expression,
      aux_sym__string_quoted_repeat1,
  [1289] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__quoted_string_content,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    ACTIONS(238), 1,
      anon_sym_BSLASH,
    STATE(58), 2,
      sym_template_expression,
      aux_sym__string_quoted_repeat1,
  [1306] = 5,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_BSLASH,
    ACTIONS(241), 1,
      sym__quoted_string_content,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    STATE(58), 2,
      sym_template_expression,
      aux_sym__string_quoted_repeat1,
  [1323] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1351] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(74), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1381] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 4,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1407] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_identifier,
    ACTIONS(265), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_properties_repeat1,
    STATE(91), 1,
      sym_property,
  [1423] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_package,
    ACTIONS(269), 1,
      anon_sym_import,
    ACTIONS(271), 1,
      anon_sym_document,
    ACTIONS(273), 1,
      anon_sym_component,
  [1439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(61), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1453] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1469] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1483] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1499] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(84), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1513] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_properties_repeat1,
    STATE(91), 1,
      sym_property,
  [1529] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1543] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_import,
    ACTIONS(271), 1,
      anon_sym_document,
    ACTIONS(273), 1,
      anon_sym_component,
    ACTIONS(283), 1,
      anon_sym_using,
  [1559] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_properties_repeat1,
    STATE(91), 1,
      sym_property,
  [1575] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
    ACTIONS(289), 1,
      anon_sym_LPAREN2,
    STATE(77), 2,
      sym_import_declaration,
      aux_sym__imports,
  [1589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 4,
      anon_sym_DQUOTE,
      anon_sym_DASH_DASH,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
  [1599] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
    ACTIONS(296), 1,
      anon_sym_LPAREN2,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1613] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
    ACTIONS(301), 1,
      anon_sym_LPAREN2,
    STATE(80), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
  [1627] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(304), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1643] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_identifier,
    ACTIONS(308), 1,
      anon_sym_LBRACK,
    STATE(125), 1,
      sym__using_multiple,
    STATE(126), 1,
      sym__using_single,
  [1659] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(60), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      anon_sym_LPAREN2,
    STATE(79), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [1687] = 2,
    ACTIONS(124), 1,
      sym_comment,
    ACTIONS(205), 3,
      sym__quoted_string_content,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
  [1696] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_identifier,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym__using_multiple_repeat1,
  [1709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
    STATE(136), 2,
      sym__identifier_or_member_access,
      sym_member_access,
  [1720] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_document,
    ACTIONS(273), 1,
      anon_sym_component,
    ACTIONS(283), 1,
      anon_sym_using,
  [1733] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
    STATE(90), 2,
      sym__identifier_or_member_access,
      sym_member_access,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1753] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(319), 2,
      sym_identifier,
      anon_sym_RBRACK,
  [1764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(325), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym__using_multiple_repeat1,
  [1777] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(327), 2,
      sym_identifier,
      anon_sym_RBRACK,
  [1788] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(331), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1808] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_import,
    ACTIONS(271), 1,
      anon_sym_document,
    ACTIONS(273), 1,
      anon_sym_component,
  [1821] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
    ACTIONS(339), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_properties,
  [1834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
    STATE(11), 2,
      sym__identifier_or_member_access,
      sym_member_access,
  [1845] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(341), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      aux_sym__using_multiple_repeat1,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(132), 1,
      sym__string_quoted,
  [1884] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(119), 1,
      sym__string_quoted,
  [1894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1902] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym_properties,
  [1912] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_properties,
  [1922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 2,
      sym_identifier,
      anon_sym_RBRACK,
  [1930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1938] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_identifier,
    STATE(12), 1,
      sym_member_access,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [1996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN2,
  [2004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      sym_identifier,
      anon_sym_RBRACK,
  [2012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_RPAREN,
  [2019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_RPAREN,
  [2026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_RPAREN,
  [2033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      ts_builtin_sym_end,
  [2040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_RPAREN,
  [2047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_LPAREN,
  [2054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_using,
  [2061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      sym_identifier,
  [2068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      sym_identifier,
  [2075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      sym_identifier,
  [2082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
  [2089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
  [2096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_COLON,
  [2103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_RPAREN,
  [2110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_RPAREN,
  [2117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_import,
  [2124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      sym_identifier,
  [2131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_COLON,
  [2138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_LBRACE,
  [2145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      sym_identifier,
  [2152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_component,
  [2159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_identifier,
  [2166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_RPAREN,
  [2173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_RPAREN,
  [2180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      sym_identifier,
  [2187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      sym_identifier,
  [2194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_LPAREN,
  [2201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 79,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 155,
  [SMALL_STATE(7)] = 193,
  [SMALL_STATE(8)] = 218,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 322,
  [SMALL_STATE(12)] = 358,
  [SMALL_STATE(13)] = 380,
  [SMALL_STATE(14)] = 401,
  [SMALL_STATE(15)] = 422,
  [SMALL_STATE(16)] = 452,
  [SMALL_STATE(17)] = 482,
  [SMALL_STATE(18)] = 512,
  [SMALL_STATE(19)] = 533,
  [SMALL_STATE(20)] = 558,
  [SMALL_STATE(21)] = 585,
  [SMALL_STATE(22)] = 612,
  [SMALL_STATE(23)] = 630,
  [SMALL_STATE(24)] = 648,
  [SMALL_STATE(25)] = 670,
  [SMALL_STATE(26)] = 692,
  [SMALL_STATE(27)] = 710,
  [SMALL_STATE(28)] = 738,
  [SMALL_STATE(29)] = 756,
  [SMALL_STATE(30)] = 774,
  [SMALL_STATE(31)] = 792,
  [SMALL_STATE(32)] = 820,
  [SMALL_STATE(33)] = 838,
  [SMALL_STATE(34)] = 866,
  [SMALL_STATE(35)] = 888,
  [SMALL_STATE(36)] = 913,
  [SMALL_STATE(37)] = 932,
  [SMALL_STATE(38)] = 957,
  [SMALL_STATE(39)] = 982,
  [SMALL_STATE(40)] = 1007,
  [SMALL_STATE(41)] = 1027,
  [SMALL_STATE(42)] = 1047,
  [SMALL_STATE(43)] = 1063,
  [SMALL_STATE(44)] = 1079,
  [SMALL_STATE(45)] = 1099,
  [SMALL_STATE(46)] = 1113,
  [SMALL_STATE(47)] = 1134,
  [SMALL_STATE(48)] = 1155,
  [SMALL_STATE(49)] = 1176,
  [SMALL_STATE(50)] = 1188,
  [SMALL_STATE(51)] = 1200,
  [SMALL_STATE(52)] = 1212,
  [SMALL_STATE(53)] = 1224,
  [SMALL_STATE(54)] = 1236,
  [SMALL_STATE(55)] = 1248,
  [SMALL_STATE(56)] = 1260,
  [SMALL_STATE(57)] = 1272,
  [SMALL_STATE(58)] = 1289,
  [SMALL_STATE(59)] = 1306,
  [SMALL_STATE(60)] = 1323,
  [SMALL_STATE(61)] = 1337,
  [SMALL_STATE(62)] = 1351,
  [SMALL_STATE(63)] = 1367,
  [SMALL_STATE(64)] = 1381,
  [SMALL_STATE(65)] = 1397,
  [SMALL_STATE(66)] = 1407,
  [SMALL_STATE(67)] = 1423,
  [SMALL_STATE(68)] = 1439,
  [SMALL_STATE(69)] = 1453,
  [SMALL_STATE(70)] = 1469,
  [SMALL_STATE(71)] = 1483,
  [SMALL_STATE(72)] = 1499,
  [SMALL_STATE(73)] = 1513,
  [SMALL_STATE(74)] = 1529,
  [SMALL_STATE(75)] = 1543,
  [SMALL_STATE(76)] = 1559,
  [SMALL_STATE(77)] = 1575,
  [SMALL_STATE(78)] = 1589,
  [SMALL_STATE(79)] = 1599,
  [SMALL_STATE(80)] = 1613,
  [SMALL_STATE(81)] = 1627,
  [SMALL_STATE(82)] = 1643,
  [SMALL_STATE(83)] = 1659,
  [SMALL_STATE(84)] = 1673,
  [SMALL_STATE(85)] = 1687,
  [SMALL_STATE(86)] = 1696,
  [SMALL_STATE(87)] = 1709,
  [SMALL_STATE(88)] = 1720,
  [SMALL_STATE(89)] = 1733,
  [SMALL_STATE(90)] = 1744,
  [SMALL_STATE(91)] = 1753,
  [SMALL_STATE(92)] = 1764,
  [SMALL_STATE(93)] = 1777,
  [SMALL_STATE(94)] = 1788,
  [SMALL_STATE(95)] = 1799,
  [SMALL_STATE(96)] = 1808,
  [SMALL_STATE(97)] = 1821,
  [SMALL_STATE(98)] = 1834,
  [SMALL_STATE(99)] = 1845,
  [SMALL_STATE(100)] = 1858,
  [SMALL_STATE(101)] = 1866,
  [SMALL_STATE(102)] = 1874,
  [SMALL_STATE(103)] = 1884,
  [SMALL_STATE(104)] = 1894,
  [SMALL_STATE(105)] = 1902,
  [SMALL_STATE(106)] = 1912,
  [SMALL_STATE(107)] = 1922,
  [SMALL_STATE(108)] = 1930,
  [SMALL_STATE(109)] = 1938,
  [SMALL_STATE(110)] = 1948,
  [SMALL_STATE(111)] = 1956,
  [SMALL_STATE(112)] = 1964,
  [SMALL_STATE(113)] = 1972,
  [SMALL_STATE(114)] = 1980,
  [SMALL_STATE(115)] = 1988,
  [SMALL_STATE(116)] = 1996,
  [SMALL_STATE(117)] = 2004,
  [SMALL_STATE(118)] = 2012,
  [SMALL_STATE(119)] = 2019,
  [SMALL_STATE(120)] = 2026,
  [SMALL_STATE(121)] = 2033,
  [SMALL_STATE(122)] = 2040,
  [SMALL_STATE(123)] = 2047,
  [SMALL_STATE(124)] = 2054,
  [SMALL_STATE(125)] = 2061,
  [SMALL_STATE(126)] = 2068,
  [SMALL_STATE(127)] = 2075,
  [SMALL_STATE(128)] = 2082,
  [SMALL_STATE(129)] = 2089,
  [SMALL_STATE(130)] = 2096,
  [SMALL_STATE(131)] = 2103,
  [SMALL_STATE(132)] = 2110,
  [SMALL_STATE(133)] = 2117,
  [SMALL_STATE(134)] = 2124,
  [SMALL_STATE(135)] = 2131,
  [SMALL_STATE(136)] = 2138,
  [SMALL_STATE(137)] = 2145,
  [SMALL_STATE(138)] = 2152,
  [SMALL_STATE(139)] = 2159,
  [SMALL_STATE(140)] = 2166,
  [SMALL_STATE(141)] = 2173,
  [SMALL_STATE(142)] = 2180,
  [SMALL_STATE(143)] = 2187,
  [SMALL_STATE(144)] = 2194,
  [SMALL_STATE(145)] = 2201,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(18),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(57),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(26),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(30),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(19),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, .production_id = 10),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, .production_id = 10),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(57),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(25),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(98),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(87),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(81),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, .production_id = 11),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, .production_id = 11),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_quoted, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_quoted, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_quoted, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_quoted, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary_expression, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expression, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__element_content, 1),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__element_content_repeat1, 2), SHIFT_REPEAT(57),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__element_content_repeat1, 2), SHIFT_REPEAT(25),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__element_content_repeat1, 2),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__element_content_repeat1, 2), SHIFT_REPEAT(98),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifier_or_member_access, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary_expression, 1, .production_id = 9),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expression, 1, .production_id = 9),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_line, 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_line, 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 12),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 12),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, .production_id = 16),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 16),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_line_repeat1, 2),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_line_repeat1, 2), SHIFT_REPEAT(34),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_line_repeat1, 2), SHIFT_REPEAT(145),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 1, .production_id = 13),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 1, .production_id = 13),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__element_content_repeat1, 2), SHIFT_REPEAT(41),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_line_repeat1, 2), SHIFT_REPEAT(40),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_line_repeat1, 2), SHIFT_REPEAT(144),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 13),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 13),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_expression, 4),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 5, .production_id = 14),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4, .production_id = 14),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, .production_id = 5),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, .production_id = 5),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_quoted_repeat1, 2), SHIFT_REPEAT(58),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_quoted_repeat1, 2),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__string_quoted_repeat1, 2), SHIFT_REPEAT(123),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2), SHIFT_REPEAT(135),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 3),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2), SHIFT_REPEAT(130),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__imports, 2),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__imports, 2), SHIFT_REPEAT(133),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 2),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(138),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [301] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [310] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, .production_id = 7), SHIFT_REPEAT(93),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, .production_id = 7),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, .production_id = 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 1),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 1, .production_id = 1),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 1),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 15),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 5, .production_id = 3),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 6, .production_id = 3),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, .production_id = 1),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 4),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_using_declaration, 5, .production_id = 8),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 5, .production_id = 2),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 5, .production_id = 2),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 6, .production_id = 3),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 5, .production_id = 3),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 5),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [371] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_single, 1, .production_id = 1),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_multiple, 3, .production_id = 6),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_multiple, 2),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_teml_external_scanner_create(void);
void tree_sitter_teml_external_scanner_destroy(void *);
bool tree_sitter_teml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_teml_external_scanner_serialize(void *, char *);
void tree_sitter_teml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_teml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_teml_external_scanner_create,
      tree_sitter_teml_external_scanner_destroy,
      tree_sitter_teml_external_scanner_scan,
      tree_sitter_teml_external_scanner_serialize,
      tree_sitter_teml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
