/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__identifier_simple = 1,
  sym_comment = 2,
  anon_sym_SLASH = 3,
  sym__string_quoted = 4,
  anon_sym_LPAREN = 5,
  anon_sym_package = 6,
  anon_sym_RPAREN = 7,
  anon_sym_import = 8,
  anon_sym_LBRACK = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACK = 11,
  anon_sym_using = 12,
  anon_sym_document = 13,
  anon_sym_component = 14,
  anon_sym_COLON = 15,
  sym_source_file = 16,
  sym__identifier_qualified = 17,
  sym_identifier = 18,
  sym_package_declaration = 19,
  sym_import_declaration = 20,
  sym__using_single = 21,
  sym__using_multiple = 22,
  sym_using_declaration = 23,
  sym_document_declaration = 24,
  sym_component_declaration = 25,
  sym_properties = 26,
  sym_property = 27,
  aux_sym__imports = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_source_file_repeat2 = 30,
  aux_sym__identifier_qualified_repeat1 = 31,
  aux_sym__using_multiple_repeat1 = 32,
  aux_sym_properties_repeat1 = 33,
  anon_alias_sym_simple = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__identifier_simple] = "_identifier_simple",
  [sym_comment] = "comment",
  [anon_sym_SLASH] = "/",
  [sym__string_quoted] = "string",
  [anon_sym_LPAREN] = "(",
  [anon_sym_package] = "package",
  [anon_sym_RPAREN] = ")",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_using] = "using",
  [anon_sym_document] = "document",
  [anon_sym_component] = "component",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym__identifier_qualified] = "qualified",
  [sym_identifier] = "identifier",
  [sym_package_declaration] = "package_declaration",
  [sym_import_declaration] = "import_declaration",
  [sym__using_single] = "_using_single",
  [sym__using_multiple] = "_using_multiple",
  [sym_using_declaration] = "using_declaration",
  [sym_document_declaration] = "document_declaration",
  [sym_component_declaration] = "component_declaration",
  [sym_properties] = "properties",
  [sym_property] = "property",
  [aux_sym__imports] = "_imports",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym__identifier_qualified_repeat1] = "_identifier_qualified_repeat1",
  [aux_sym__using_multiple_repeat1] = "_using_multiple_repeat1",
  [aux_sym_properties_repeat1] = "properties_repeat1",
  [anon_alias_sym_simple] = "simple",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__identifier_simple] = sym__identifier_simple,
  [sym_comment] = sym_comment,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym__string_quoted] = sym__string_quoted,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_document] = anon_sym_document,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym__identifier_qualified] = sym__identifier_qualified,
  [sym_identifier] = sym_identifier,
  [sym_package_declaration] = sym_package_declaration,
  [sym_import_declaration] = sym_import_declaration,
  [sym__using_single] = sym__using_single,
  [sym__using_multiple] = sym__using_multiple,
  [sym_using_declaration] = sym_using_declaration,
  [sym_document_declaration] = sym_document_declaration,
  [sym_component_declaration] = sym_component_declaration,
  [sym_properties] = sym_properties,
  [sym_property] = sym_property,
  [aux_sym__imports] = aux_sym__imports,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym__identifier_qualified_repeat1] = aux_sym__identifier_qualified_repeat1,
  [aux_sym__using_multiple_repeat1] = aux_sym__using_multiple_repeat1,
  [aux_sym_properties_repeat1] = aux_sym_properties_repeat1,
  [anon_alias_sym_simple] = anon_alias_sym_simple,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier_simple] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__string_quoted] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_document] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_qualified] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__using_single] = {
    .visible = false,
    .named = true,
  },
  [sym__using_multiple] = {
    .visible = false,
    .named = true,
  },
  [sym_using_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_document_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__imports] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__identifier_qualified_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__using_multiple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_properties_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_simple] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_from = 1,
  field_name = 2,
  field_path = 3,
  field_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 2},
    {field_path, 3},
  [3] =
    {field_name, 2},
  [4] =
    {field_name, 0},
    {field_type, 2},
  [6] =
    {field_name, 1, .inherited = true},
  [7] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [9] =
    {field_from, 3},
    {field_name, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_identifier,
  },
  [2] = {
    [2] = sym_identifier,
  },
  [3] = {
    [2] = sym_identifier,
  },
  [4] = {
    [0] = anon_alias_sym_simple,
  },
  [5] = {
    [0] = sym_identifier,
  },
  [8] = {
    [3] = sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '(', 9,
        ')', 10,
        ',', 12,
        '/', 7,
        ':', 14,
        '[', 11,
        ']', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '(', 9,
        ')', 10,
        ',', 12,
        '/', 2,
        ':', 14,
        '[', 11,
        ']', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__identifier_simple);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__string_quoted);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'u') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'k') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_document);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_component);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__identifier_simple] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym__string_quoted] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_document] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym_package_declaration] = STATE(4),
    [sym_import_declaration] = STATE(2),
    [sym_document_declaration] = STATE(47),
    [sym_component_declaration] = STATE(8),
    [aux_sym__imports] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_document_declaration,
    STATE(5), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
    STATE(7), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(16), 2,
      sym_import_declaration,
      aux_sym__imports,
  [25] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_document_declaration,
    STATE(6), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
    STATE(9), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(16), 2,
      sym_import_declaration,
      aux_sym__imports,
  [50] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_document_declaration,
    STATE(3), 2,
      sym_import_declaration,
      aux_sym__imports,
    STATE(7), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [71] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_document_declaration,
    STATE(9), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(19), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
  [92] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(75), 1,
      sym_document_declaration,
    STATE(11), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
    STATE(19), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
  [113] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_document_declaration,
    STATE(17), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_document_declaration,
    STATE(17), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [147] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(75), 1,
      sym_document_declaration,
    STATE(17), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [164] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      aux_sym__identifier_qualified_repeat1,
    ACTIONS(23), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [179] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(59), 1,
      sym_document_declaration,
    STATE(17), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [196] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      aux_sym__identifier_qualified_repeat1,
    ACTIONS(29), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      aux_sym__identifier_qualified_repeat1,
    ACTIONS(31), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [226] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_package,
    ACTIONS(38), 1,
      anon_sym_import,
    ACTIONS(40), 1,
      anon_sym_document,
    ACTIONS(42), 1,
      anon_sym_component,
  [242] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_import,
    ACTIONS(40), 1,
      anon_sym_document,
    ACTIONS(42), 1,
      anon_sym_component,
    ACTIONS(44), 1,
      anon_sym_using,
  [258] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    STATE(16), 2,
      sym_import_declaration,
      aux_sym__imports,
  [272] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    STATE(17), 2,
      sym_component_declaration,
      aux_sym_source_file_repeat2,
  [286] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym__identifier_simple,
    ACTIONS(58), 1,
      anon_sym_RBRACK,
    STATE(22), 1,
      aux_sym_properties_repeat1,
    STATE(27), 1,
      sym_property,
  [302] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    STATE(19), 2,
      sym_using_declaration,
      aux_sym_source_file_repeat1,
  [316] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym__identifier_simple,
    ACTIONS(68), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_properties_repeat1,
    STATE(27), 1,
      sym_property,
  [332] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym__identifier_simple,
    ACTIONS(72), 1,
      anon_sym_LBRACK,
    STATE(45), 1,
      sym__using_multiple,
    STATE(48), 1,
      sym__using_single,
  [348] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      sym__identifier_simple,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_properties_repeat1,
    STATE(27), 1,
      sym_property,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_SLASH,
    ACTIONS(31), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [385] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym__identifier_simple,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(49), 1,
      sym_properties,
  [398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_document,
    ACTIONS(42), 1,
      anon_sym_component,
    ACTIONS(44), 1,
      anon_sym_using,
  [411] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(84), 2,
      sym__identifier_simple,
      anon_sym_RBRACK,
  [422] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__identifier_simple,
    STATE(24), 1,
      sym_identifier,
    STATE(30), 1,
      sym__identifier_qualified,
  [435] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym__identifier_simple,
    ACTIONS(92), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      aux_sym__using_multiple_repeat1,
  [448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 3,
      sym__identifier_simple,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    ACTIONS(96), 2,
      sym__identifier_simple,
      anon_sym_RBRACK,
  [468] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym__identifier_simple,
    ACTIONS(100), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym__using_multiple_repeat1,
  [481] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym__identifier_simple,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym__using_multiple_repeat1,
  [494] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_import,
    ACTIONS(40), 1,
      anon_sym_document,
    ACTIONS(42), 1,
      anon_sym_component,
  [507] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(72), 1,
      sym_properties,
  [517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 2,
      sym__identifier_simple,
      anon_sym_RBRACK,
  [541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_document,
    ACTIONS(42), 1,
      anon_sym_component,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      sym__identifier_simple,
      anon_sym_RBRACK,
  [567] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(60), 1,
      sym_properties,
  [593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym__identifier_simple,
  [600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym__identifier_simple,
  [607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
  [614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym__identifier_simple,
  [621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
  [628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_using,
  [635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_import,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
  [649] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
  [656] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym__identifier_simple,
  [663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_component,
  [670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
  [677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
  [684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
  [691] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
  [698] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
  [705] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym__identifier_simple,
  [712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_COLON,
  [719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
  [726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
  [733] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym__identifier_simple,
  [740] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [747] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym__string_quoted,
  [754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
  [761] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym__identifier_simple,
  [768] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym__identifier_simple,
  [775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
  [789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym__identifier_simple,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__string_quoted,
  [803] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 71,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 113,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 147,
  [SMALL_STATE(10)] = 164,
  [SMALL_STATE(11)] = 179,
  [SMALL_STATE(12)] = 196,
  [SMALL_STATE(13)] = 211,
  [SMALL_STATE(14)] = 226,
  [SMALL_STATE(15)] = 242,
  [SMALL_STATE(16)] = 258,
  [SMALL_STATE(17)] = 272,
  [SMALL_STATE(18)] = 286,
  [SMALL_STATE(19)] = 302,
  [SMALL_STATE(20)] = 316,
  [SMALL_STATE(21)] = 332,
  [SMALL_STATE(22)] = 348,
  [SMALL_STATE(23)] = 364,
  [SMALL_STATE(24)] = 376,
  [SMALL_STATE(25)] = 385,
  [SMALL_STATE(26)] = 398,
  [SMALL_STATE(27)] = 411,
  [SMALL_STATE(28)] = 422,
  [SMALL_STATE(29)] = 435,
  [SMALL_STATE(30)] = 448,
  [SMALL_STATE(31)] = 457,
  [SMALL_STATE(32)] = 468,
  [SMALL_STATE(33)] = 481,
  [SMALL_STATE(34)] = 494,
  [SMALL_STATE(35)] = 507,
  [SMALL_STATE(36)] = 517,
  [SMALL_STATE(37)] = 525,
  [SMALL_STATE(38)] = 533,
  [SMALL_STATE(39)] = 541,
  [SMALL_STATE(40)] = 551,
  [SMALL_STATE(41)] = 559,
  [SMALL_STATE(42)] = 567,
  [SMALL_STATE(43)] = 575,
  [SMALL_STATE(44)] = 583,
  [SMALL_STATE(45)] = 593,
  [SMALL_STATE(46)] = 600,
  [SMALL_STATE(47)] = 607,
  [SMALL_STATE(48)] = 614,
  [SMALL_STATE(49)] = 621,
  [SMALL_STATE(50)] = 628,
  [SMALL_STATE(51)] = 635,
  [SMALL_STATE(52)] = 642,
  [SMALL_STATE(53)] = 649,
  [SMALL_STATE(54)] = 656,
  [SMALL_STATE(55)] = 663,
  [SMALL_STATE(56)] = 670,
  [SMALL_STATE(57)] = 677,
  [SMALL_STATE(58)] = 684,
  [SMALL_STATE(59)] = 691,
  [SMALL_STATE(60)] = 698,
  [SMALL_STATE(61)] = 705,
  [SMALL_STATE(62)] = 712,
  [SMALL_STATE(63)] = 719,
  [SMALL_STATE(64)] = 726,
  [SMALL_STATE(65)] = 733,
  [SMALL_STATE(66)] = 740,
  [SMALL_STATE(67)] = 747,
  [SMALL_STATE(68)] = 754,
  [SMALL_STATE(69)] = 761,
  [SMALL_STATE(70)] = 768,
  [SMALL_STATE(71)] = 775,
  [SMALL_STATE(72)] = 782,
  [SMALL_STATE(73)] = 789,
  [SMALL_STATE(74)] = 796,
  [SMALL_STATE(75)] = 803,
  [SMALL_STATE(76)] = 810,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 4),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__identifier_qualified, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__identifier_qualified_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__identifier_qualified_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__imports, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__imports, 2, 0, 0), SHIFT_REPEAT(51),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(55),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__identifier_qualified_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_properties_repeat1, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 1, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, 0, 7), SHIFT_REPEAT(31),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, 0, 7),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 5, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 5, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 5, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__using_multiple_repeat1, 2, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_using_declaration, 5, 0, 8),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_single, 1, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 5, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_multiple, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__using_multiple, 3, 0, 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_declaration, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_teml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__identifier_simple,
    .primary_state_ids = ts_primary_state_ids,
    .name = "teml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
